### ISSUE TITLE
netlink_kernel_create（）函数您采用的是最新的吗？

### ISSUE THREAD

**Issue by anonymity12** [wangzhangjun/netlinkdemo#1]
是的，我这个是4.4.0内核版本的，具体你可以看你的内核版本
是的，我这个是4.4.0内核版本的，具体你可以看你的内核版本。。我再网上看到这样参数的netlink_kernel_create函数，（都是很老的博客文章）
```c
netlink_kernel_create(NETLINK_GENERIC, 0, recv_handler, THIS_MODULE);
```
而您在使用的是：
```c
nl_sk = netlink_kernel_create(&init_net, NETLINK_TEST, &cfg);
```

可否告知 ，我可以从哪里得到这个新函数的使用详解，或者您看那本书，或者资料？（我老师发给我的似乎都是针对linux2.6的）
是的，我这个是4.4.0内核版本的，具体你可以看你的内核版本。

**Comment by wangzhangjun** [comment]
netlink 是根据内核版本变化的。我这个是在4.4.0上的使用。具体你可以看看你对应的那个内核版本的这个函数声明

**Comment by anonymity12** [comment]
谢谢回复，我还不会追踪源代码，我会修改一下您的部分代码实现我自己的功能，后期有时间再探究一下，请问netlink这块您是怎么学习的？有任何资料推荐吗？

**Comment by wangzhangjun** [comment]
最好的办法还是看源码，你可以https://elixir.bootlin.com/linux/v4.4/source/include/linux/syscalls.h#L517，在这里搜索你需要的函数，查看他的声明。

**Comment by anonymity12** [comment]
非常有用的网站，谢谢
